--- 
title: 'Developing the Cycling Environmental Composite Index (CECI) to Assess Cycling Friendliness: Evidence from London'

author: 
- |
    | Yifan Wu
    |    
    | CASA0010, MSc Urban Spatial Science Dissertation 
    |  
    | Supervisor: Dr Duncan Smith
    |
    | Thesis Repository: https://van-wu1.github.io/CASA-MSc-thesis/
    |  
    | Project repository (code): https://github.com/Van-Wu1/CECI.git
    |
    | This dissertation is submitted in part requirement for the 
    | MSc in the Centre for Advanced Spatial Analysis, 
    | Bartlett Faculty of the Built Environment, UCL
    |
    | Word count: 11,066

date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
classoption: oneside #openany or #twosides #if two then need to change headers and check margins.
geometry: "left=4cm, right=3cm, top=2.5cm, bottom=2.5cm"
fontsize: 12pt
linestretch: 1.5
bibliography: [book.bib, packages.bib, test.bib]
biblio-style: apa
link-citations: yes
github-repo: Van-Wu1/CASA-MSc-thesis
description: "This dissertation is submitted in part requirement for the MSc in the Centre for Advanced Spatial Analysis, Bartlett Faculty of the Built Environment, UCL "
always_allow_html: yes

header-includes:
  - \usepackage{float}      # 支持 [H] 固定图表位置
---

```{=latex}
\pagenumbering{roman}
```

```{r include=FALSE}
library(knitr)
```

`r if (knitr:::is_html_output()) '
# Abstract {-}
'`
`r if (knitr:::is_latex_output()) '
# Abstract {.unlisted .unnumbered}
'`

This study develops a composite framework to evaluate the cycling environment in London, integrating structural rideability, environmental perception, and network centrality into a unified Cycling Environment Composite Index (CECI). Using multi-source datasets, including OpenStreetMap, environmental indicators, and graph-based network measures, the analysis identifies both local and city-wide constraints shaping ridership potential. The results reveal a pronounced core–periphery gradient: central London suffers from fragmented infrastructure, high traffic stress, and environmental burdens, while outer areas contain isolated yet high-quality segments often linked to green corridors. By combining facility-level attributes with spatial accessibility and environmental quality, the CECI provides a holistic measure that highlights critical gaps in network continuity and equity. The study contributes methodologically by operationalising a multi-dimensional index and empirically by mapping London’s cycling disparities. Findings support evidence-based interventions for sustainable mobility, emphasising the need to strengthen central connections, reduce environmental stressors, and extend high-quality cycling corridors into cohesive metropolitan networks.


